### ISSUE TITLE
Support SDL 2.0.9

### ISSUE THREAD

**Issue by dkorpel** [p0nce/turtle#4]
I couldn't run the examples because "SDL One or more symbols failed to load.". It turns out turtle targets SDL 2.0.10 and my Debian package just had to be SDL 2.0.9. I downgraded turtle to use SDL_209 and could run the examples, which made me wonder if there's a reason to target 2.0.10 specifically. Do you need specific SDL functionality or can turtle require a lower SDL version?

**Comment by p0nce** [comment]
I think we can go lower.

**Comment by p0nce** [comment]
This is in v0.0.11
